feat(content-band-list-block): Content band list block.
hlxsites/merative2 pull request #288
Opened 2023-07-19 14:17 UTC by nimithshetty17

## Issue

Fixes #[MERATIVE-781](https://jira.sdlc.merative.com/browse/MERATIVE-781)

## Description

> This ticket is part of the phase 3 effort, which is to migrate all of the remaining components/patterns in AEM over to Franklin.  Sections > Section Content band list
Note: part of this work is to clean up the naming in Franklin to ensure it aligns with our Design Systems.

**New**

![image](https://github.com/hlxsites/merative2/assets/111452145/6dad38eb-87bc-4470-87e4-9bc0f89c061f)

## Design Specs

> If applicable, add the direct link to the design specs of the component/feature that's part of this PR.

- Figma Link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=1459-14993&mode=design&t=WtS8KBTRL2E1rFnO-0

## Test URLs
  
https://content-band-list-block--merative2--nimithshetty17.hlx.page/block-library/sections/section-content-band-list
  
## Testing Instruction

>To test the content band list and its responsiveness with respect to the design across all devices.

2023-07-20 09:42 UTC, sachinmesh requested changes
1. Arrow dimension should be as per design. Right now they are big. The spacing between arrow and the text should be 10px in all variations. 
<img width="235" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/09ee68a6-569c-4717-a5f2-2f283b50ba60">

2. Spacing between bottom right corner illustration with above standalone links should be 48px in all variations at all breakpoints as well. 
<img width="1352" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/5ae644bf-22f6-4860-8ff3-2ed8d10832fe">

3. The Title text width container in content band list side text component should be 648px similar to other variations.
<img width="1184" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/055e6c25-8904-4cd4-b656-fd16be0cbc10">

4. In mobile the spacing between the icon and the stand alone link above it should be 48px.
<img width="344" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/8dc7186d-b781-4ed3-9c5b-d62cbbe0d689">

2023-07-20 13:51 UTC, proeung requested changes
There's a lot of duplication styling that's not needed. Please see my reviews above. Also, the rendering of the variation with the sidebar area is incorrect.

![Screen Shot 2023-07-20 at 9 46 36 AM](https://github.com/hlxsites/merative2/assets/1815714/e1581aa4-3571-4425-befc-91403c7abbaf)

Let's remove the variation with the checkmarks in the Content Band List Sharepoint doc since this the checkmarks will be accounted for in this section (https://main--merative2--hlxsites.hlx.page/block-library/sections/section-content-band-checkmarks), which @keith-kaplan added to this ticket (https://jira.sdlc.merative.com/browse/MERATIVE-780).

2023-07-20 13:51 UTC, proeung commented on blocks/content-intro/content-into.js
> +export default function decorate(block) {
Typo: File should be called `content-intro.js` instead of `content-into.js`

2023-07-20 13:51 UTC, proeung commented on blocks/content-intro/content-into.js
> +  block.innerHTML = finalComponent.innerHTML;
Not sure what's the purpose of this script. We don't need to manipulate the dom elements to display the content intro block with a side area. That can be handled in the CSS.

This block structure should output a markup that allows you to style in CSS.

![Screen Shot 2023-07-20 at 9 44 34 AM](https://github.com/hlxsites/merative2/assets/1815714/55bf1e8d-a411-4ba6-8875-a3ad12334e60)

2023-07-25 09:44 UTC, nimithshetty17 commented
@sachinmesh @proeung - Have made all the requested changes. Please have a look and let me know if there are any concerns.

2023-07-25 10:36 UTC, sachinmesh commented
HI @nimithshetty17 
Checked this testing URL https://content-band-list-block--merative2--nimithshetty17.hlx.page/block-library/sections/section-content-band-list

These still needs to be done 
<img width="820" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/48ae1e0e-94dd-4040-b524-8ce074a038d7">

<img width="821" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/13b26c0d-be21-4edd-bf58-2ccdd62cf19b">

2023-07-26 05:14 UTC, nimithshetty17 commented
Branch not getting updated with the latest commits.

2023-07-26 05:14 UTC, closed without merging