784 video promo
hlxsites/merative2 pull request #307
Opened 2023-08-02 11:10 UTC by sahmad-merative

Multiple Youtube video issue fixes

## Issue

UI fixes : fonts, padding, and alingments

Fixes #<gh-issue-id>

## Description
aligned design according to figma
fixed multiple youtube video on a page issue

## Design Specs

- Figma Link -https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=1641%3A13366&mode=design&t=leAsxbNftxoq6gTd-1

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/block-library/blocks/video
- After (Changes from this PR):[ https://`<branch>`--merative2--`<YOUR_USERNAME>`.hlx.page](https://784-video-promo--merative2--sahmad-merative.hlx.page/drafts/saad/leadspace-test)
- https://784-video-promo--merative2--sahmad-merative.hlx.page/block-library/blocks/video
  
## Testing Instruction

> If applicable, please describe the tests that you ran to verify your changes. Provide instructions and link to the `hlx` deploy preview so that QA and the design team can provide proper testing.

<img width="845" alt="image" src="https://github.com/hlxsites/merative2/assets/135624814/dd340645-eb7c-42f4-8045-d171a263d71b">

<img width="2056" alt="image" src="https://github.com/hlxsites/merative2/assets/135624814/604fa500-9ce6-4c1f-b3c6-fdefc9a040d7">

<img width="853" alt="image" src="https://github.com/hlxsites/merative2/assets/135624814/04e3603f-593d-46e2-ab99-45debb2eb181">

<img width="2056" alt="image" src="https://github.com/hlxsites/merative2/assets/135624814/0afe761b-3047-4b69-880e-bc2eb5a6ff3c">

2023-08-02 15:33 UTC, proeung commented
@sahmad-merative Just a couple of notes before I start to review this PR.

- Please make sure you have the proper title for the PR. Currently, it's set to `784 video promo` and it needs to be descriptive and follows the conventional commit message format (eg. `fix(video): aligned to design & addressed youtube loading issue`
- Make sure the PR description area has a proper change list.
- Provide testing instruction for QA (@sharathmrft ) and stakeholders (@keith-kaplan) - See example here - https://github.com/hlxsites/merative2/pull/302#issue-1825111151

2023-08-03 12:50 UTC, sharathmrft requested changes
@sahmad-merative 
1.Video is  not playing for Carbon with video on left.

2023-08-04 10:52 UTC, sharathmrft commented
@sahmad-merative 

Background You tube Video player issue is Tested it is working as expected

@proeung

2023-08-04 11:51 UTC, sachinmesh requested changes
1. Eyebrow font style is wrong.
2. Eyebrow - 32px spacing - Titile - 32px spacing - Bodycopy
3. The component should be end to end , no padding on left and right side.
4. Width of this video block should be 744 x 420px.


     
<img width="1139" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/879042d8-db7b-4b1c-89d2-cc831cf232e9">


@sahmad-merative @sharathmrft @proeung

2023-08-07 15:13 UTC, proeung requested changes
@sahmad-merative Looks good! I just have a comment about the removal of the `data-hj-allow-iframe` attribute that's needed within the YT iframe code.

Also, @amol-anand or @helms-charity Can you help review this PR? There are a good amount of code changes within the `video.js` that would be great for you to take a look and make sure we're not missing anything.

2023-08-07 15:13 UTC, proeung commented on blocks/video/video.js
> -  iframe.setAttribute('data-hj-allow-iframe', '');
This code should not be removed. We need to add the `data-hj-allow-iframe` to the YT iframe.

2023-08-08 18:19 UTC, proeung approved these changes
@sahmad-merative Thanks for addressing my feedback. Everything looks good from a code perspective.

I'll defer to @sachinmesh and @sharathmrft to verify the design QA and browser testing portions.

2023-08-09 11:44 UTC, sharathmrft approved these changes
@sahmad-merative You tube player is verified it is working as expected and verified in different browsers as well.
@proeung @Shalini-SB

2023-08-09 12:21 UTC, sachinmesh approved these changes

2023-08-09 14:59 UTC, merged