feat(section-Image-flush-bottom ): add image-flush-bottom section.
hlxsites/merative2 pull request #312
Opened 2023-08-08 10:16 UTC by nimithshetty17

## Issue

Fixes #[MERATIVE-782](https://jira.sdlc.merative.com/browse/MERATIVE-782)

## Description

To create a new section and variations for this called "Image band - flush bottom"

**New**

![Uploading image.png…]()

## Design Specs

> If applicable, add the direct link to the design specs of the component/feature that's part of this PR.

- Figma Link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=1459-19541&mode=design&t=moJo2KW9FFraRerT-0

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--nimithshetty17.hlx.page/block-library/sections/section-image-band-flush-bottom
- After (Changes from this PR): https://section-image-flush-bottom--merative2--nimithshetty17.hlx.page/block-library/sections/section-image-band-flush-bottom
  
## Testing Instruction

To test the section image flush bottom with brand logo and its responsiveness with respect to the design across all devices.

-

2023-08-08 10:48 UTC, sachinmesh commented
HI,

1. Image outline is missing in all breakpoints except the gradient one.

<img width="555" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/a050877e-4d3a-4283-9459-60a8b09af17f">

REst is good to go.

@proeung @nimithshetty17 @keith-kaplan @Shalini-SB

2023-08-08 10:51 UTC, sachinmesh requested changes
Image outline is missing

2023-08-09 13:01 UTC, nimithshetty17 commented
@sachinmesh - Please check now.

2023-08-09 13:08 UTC, sachinmesh approved these changes
All issues are fixed, good to go.

@nimithshetty17 @proeung @sharathmrft @Shalini-SB

2023-08-09 15:19 UTC, proeung commented on blocks/image-flush-bottom/image-flush-bottom.css
> +div:first-child.image-flush-bottom-wrapper,
```suggestion
main .section.image-flush-bottom-container > .image-flush-bottom-wrapper
```

Let's keep this defined to the image flush bottom section/classes.

2023-08-10 08:34 UTC, nimithshetty17 commented
@proeung - have done the changes for the same.

2023-08-10 13:45 UTC, proeung approved these changes
LGTM!

2023-08-10 13:46 UTC, merged