Creation of a solution block.
hlxsites/merative2 pull request #350
Opened 2023-10-13 08:21 UTC by nimithshetty17

Fixes #[MERATIVE-886](https://merative.atlassian.net/browse/MERATIVE-886)

## Description

The current name in Franklin for this block is a Teaser List and it only renders if a link is added for each item. We want to make this so it allows for authors to use this layout without links for each item

**New**

![image](https://github.com/hlxsites/merative2/assets/111452145/713e275f-ccf3-430c-91e7-c105064631aa)

**Changed**

![image](https://github.com/hlxsites/merative2/assets/111452145/53448920-0b7f-4dc2-bbf4-43956fbebb3a)

- Figma Link - [https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.c[…]ype=design&node-id=2969-41337&mode=design&t=FET0Yd5MWTSILb1b-4](https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=2969-41337&mode=design&t=FET0Yd5MWTSILb1b-4)
- https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=431-2354&mode=design

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/block-library/blocks/solution-list
- After (Changes from this PR): https://solution-list-block-new--merative2--nimithshetty17.hlx.page/block-library/blocks/solution-list

2023-10-13 09:13 UTC, sachinmesh requested changes
1. Only Product logo and name should be thr, not the old name 
<img width="564" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/a55f8d23-f052-44e9-9c58-b71e1d457a66">

2. bottom padding if individual then 160px and combined with other component then 96px.

2023-10-16 13:26 UTC, sachinmesh commented
Extra 160px can be seen below the cards @nimithshetty17 

<img width="606" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/c7bc1505-5e88-4750-afc2-82ae8a9e534b">

2023-10-16 13:51 UTC, keith-kaplan commented
@nimithshetty17  @sachinmesh  please see uses of the solution block in actual pages as well. See here:

https://solution-list-block-new--merative2--nimithshetty17.hlx.page/curam

2023-10-16 13:57 UTC, sachinmesh commented
> https://solution-list-block-new--merative2--nimithshetty17.hlx.page/curam

This looks good to me

2023-10-16 18:56 UTC, keith-kaplan commented
@nimithshetty17  @sachinmesh  I was looking at another page and it looks like there maybe a regression with the latest version. please take a look at screenshot - 
<img width="1274" alt="image" src="https://github.com/hlxsites/merative2/assets/111377779/876ea9b4-95b0-44b4-97cc-e12ea7b9dfd5">

https://solution-list-block-new--merative2--nimithshetty17.hlx.page/real-world-evidence

2023-10-17 05:42 UTC, sachinmesh commented
Hi @nimithshetty17 , most of the component, the 160px padding is absent. CC: @keith-kaplan 


1. There should not be any divider line here
    
<img width="981" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/68295c59-8898-432e-ba73-d856eb834b2c">


2. Here, a margin of 160px should be given above the divider line.  
<img width="994" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/9440aefd-390e-4d3f-952a-97c4dcb134c6">


3. Below the illustration 160px margin is needed in bone color. 
<img width="1155" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/51f547bf-b2d6-4298-87e7-4d23276492b6">

4. Again, 160px margin is gone here 
<img width="1048" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/4a5481d0-3739-47a7-b650-bb579eb1f654">


5. Again here, below the simple content component and the ready to talk CTA 160px margin is absent.

<img width="1132" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/fb538f2d-0730-4a06-a671-102794fb7182">

2023-10-18 11:13 UTC, sachinmesh commented
1. Background color of flexible component should be white and not bone.

<img width="1116" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/acab5533-99b2-4a50-82d6-2ff338965684">


2. The margin below the illustration should be 160px.

<img width="1111" alt="image" src="https://github.com/hlxsites/merative2/assets/124026684/2260b240-7696-4a33-a987-f76ed7e41926">


@nimithshetty17 @keith-kaplan

2023-10-18 14:23 UTC, sachinmesh approved these changes

2023-10-18 17:32 UTC, keith-kaplan approved these changes
Looks good.

2023-10-18 17:32 UTC, merged